require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Enabled: false

Style/ClassVars:
  Exclude:
    - config/initializers/devise.rb
