require: rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
