version: '3.1'

services:
  db:
    image: postgres

  web:
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - .:/srv/rails
      - /srv/rails/node_modules
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=
    depends_on:
      - db
