db:
  image: postgres
  ports:
    - "5432"

web:
  build: .
  command: bundle exec foreman start
  volumes:
    - .:/srv/rails
    - /srv/rails/node_modules
  ports:
    - "3000:3000"
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
  links:
    - db
