default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('DB_USERNAME', 'cwnmyr') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'cwnmyr') %>
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>

development:
  <<: *default
  database: cwnmyr_dev

test:
  <<: *default
  database: cwnmyr_test

production:
  <<: *default
  database: cwnmyr
