require "administrate/base_dashboard"

class InterfaceDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    host: Field::BelongsTo,
    code: Field::String,
    name: Field::String,
    interface_type: Field::BelongsTo,
    status: Field::BelongsTo,
    body: Field::Text,
    address_ipv4: Field::String,
    address_ipv6: Field::String,
    address_mac: Field::String,
    latitude: Field::Number,
    longitude: Field::Number,
    altitude: Field::Number,
    essid: Field::String,
    security_psk: Field::String,
    channel: Field::String,
    tx_power: Field::Number,
    rx_sensitivity: Field::Number,
    cable_loss: Field::Number,
    antenna_gain: Field::Number,
    beamwidth_h: Field::Number,
    beamwidth_v: Field::Number,
    azimuth: Field::Number,
    elevation: Field::Number,
    polarity: Field::String,
    interface_properties: Field::HasMany,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze

  COLLECTION_ATTRIBUTES = [
    :host,
    :code,
    :name,
    :interface_type,
    :status,
  ].freeze

  SHOW_PAGE_ATTRIBUTES = [
    :id,
    :host,
    :code,
    :name,
    :interface_type,
    :status,
    :body,
    :address_ipv4,
    :address_ipv6,
    :address_mac,
    :latitude,
    :longitude,
    :altitude,
    :essid,
    :security_psk,
    :channel,
    :tx_power,
    :rx_sensitivity,
    :cable_loss,
    :antenna_gain,
    :beamwidth_h,
    :beamwidth_v,
    :azimuth,
    :elevation,
    :polarity,
    :interface_properties,
    :created_at,
    :updated_at,
  ].freeze

  FORM_ATTRIBUTES = [
    :host,
    :code,
    :name,
    :interface_type,
    :status,
    :body,
    :address_ipv4,
    :address_ipv6,
    :address_mac,
    :latitude,
    :longitude,
    :altitude,
    :essid,
    :security_psk,
    :channel,
    :tx_power,
    :rx_sensitivity,
    :cable_loss,
    :antenna_gain,
    :beamwidth_h,
    :beamwidth_v,
    :azimuth,
    :elevation,
    :polarity,
  ].freeze

  def display_resource(status)
    "Status ##{status.to_param}"
  end
end
